/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Classes.Admin;
import java.awt.Toolkit;

/**
 *
 * @author Dell
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Admin a = new Admin();
    int roleID;
    
    public AdminFrame() {
        initComponents();
        
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListEmpRadio = new javax.swing.ButtonGroup();
        AddEmpRdio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();
        EditProfileBTN = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BTNpnl = new javax.swing.JPanel();
        AddBTN = new javax.swing.JButton();
        DelBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        UpdateBTN1 = new javax.swing.JButton();
        Container = new javax.swing.JTabbedPane();
        AddPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddTxtField = new javax.swing.JTextField();
        AddPassField = new javax.swing.JPasswordField();
        AddIdField = new javax.swing.JTextField();
        SubmitAdd = new javax.swing.JButton();
        AddInvRadio = new javax.swing.JRadioButton();
        AddMarketRadio = new javax.swing.JRadioButton();
        AddSellRadio = new javax.swing.JRadioButton();
        DeletePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        delete_emp = new javax.swing.JTable();
        SubmitDelet = new javax.swing.JButton();
        ListPnl = new javax.swing.JPanel();
        ViewTable = new javax.swing.JScrollPane();
        list_emp = new javax.swing.JTable();
        ListInvRadio = new javax.swing.JRadioButton();
        ListMarketRadio = new javax.swing.JRadioButton();
        ListSellRadio = new javax.swing.JRadioButton();
        UpdateEmp = new javax.swing.JButton();
        SearchPnl = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        empID_search = new javax.swing.JTable();
        Search = new javax.swing.JButton();
        SearchEmpID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN PAGE");
        setLocation(new java.awt.Point(200, 150));
        setMaximumSize(new java.awt.Dimension(725, 500));
        setMinimumSize(new java.awt.Dimension(725, 500));
        setName("AdminFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(725, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(725, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 119, 117));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hyper Market");

        BackBTN.setBackground(new java.awt.Color(33, 141, 138));
        BackBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setText("Home");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        EditProfileBTN.setBackground(new java.awt.Color(33, 141, 138));
        EditProfileBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EditProfileBTN.setForeground(new java.awt.Color(255, 255, 255));
        EditProfileBTN.setText("Edit Profile");
        EditProfileBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditProfileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileBTNActionPerformed(evt);
            }
        });

        BTNpnl.setBackground(new java.awt.Color(29, 119, 117));

        AddBTN.setBackground(new java.awt.Color(33, 141, 138));
        AddBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddBTN.setForeground(new java.awt.Color(255, 255, 255));
        AddBTN.setText("Add");
        AddBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        DelBTN.setBackground(new java.awt.Color(33, 141, 138));
        DelBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DelBTN.setForeground(new java.awt.Color(255, 255, 255));
        DelBTN.setText("Delete");
        DelBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBTNActionPerformed(evt);
            }
        });

        UpdateBTN.setBackground(new java.awt.Color(33, 141, 138));
        UpdateBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBTN.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBTN.setText("Search");
        UpdateBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        UpdateBTN1.setBackground(new java.awt.Color(33, 141, 138));
        UpdateBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBTN1.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBTN1.setText("List");
        UpdateBTN1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BTNpnlLayout = new javax.swing.GroupLayout(BTNpnl);
        BTNpnl.setLayout(BTNpnlLayout);
        BTNpnlLayout.setHorizontalGroup(
            BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNpnlLayout.createSequentialGroup()
                .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(DelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(UpdateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BTNpnlLayout.setVerticalGroup(
            BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Container.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        AddPnl.setBackground(new java.awt.Color(29, 119, 117));
        AddPnl.setName("AddPnl"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        AddTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTxtFieldActionPerformed(evt);
            }
        });

        AddPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassFieldActionPerformed(evt);
            }
        });

        SubmitAdd.setBackground(new java.awt.Color(33, 141, 138));
        SubmitAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitAdd.setForeground(new java.awt.Color(255, 255, 255));
        SubmitAdd.setText("Submit Adding");
        SubmitAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAddActionPerformed(evt);
            }
        });

        AddInvRadio.setBackground(new java.awt.Color(29, 119, 117));
        AddEmpRdio.add(AddInvRadio);
        AddInvRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddInvRadio.setForeground(new java.awt.Color(255, 255, 255));
        AddInvRadio.setText("Inventory Employee");
        AddInvRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInvRadioActionPerformed(evt);
            }
        });

        AddMarketRadio.setBackground(new java.awt.Color(29, 119, 117));
        AddEmpRdio.add(AddMarketRadio);
        AddMarketRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddMarketRadio.setForeground(new java.awt.Color(255, 255, 255));
        AddMarketRadio.setText("Market Employee");
        AddMarketRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMarketRadioActionPerformed(evt);
            }
        });

        AddSellRadio.setBackground(new java.awt.Color(29, 119, 117));
        AddEmpRdio.add(AddSellRadio);
        AddSellRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddSellRadio.setForeground(new java.awt.Color(255, 255, 255));
        AddSellRadio.setText("Selling Employee");
        AddSellRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSellRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPnlLayout = new javax.swing.GroupLayout(AddPnl);
        AddPnl.setLayout(AddPnlLayout);
        AddPnlLayout.setHorizontalGroup(
            AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPnlLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPnlLayout.createSequentialGroup()
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubmitAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddPnlLayout.createSequentialGroup()
                        .addComponent(AddInvRadio)
                        .addGap(18, 18, 18)
                        .addComponent(AddMarketRadio)
                        .addGap(18, 18, 18)
                        .addComponent(AddSellRadio)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        AddPnlLayout.setVerticalGroup(
            AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPnlLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddInvRadio)
                    .addComponent(AddMarketRadio)
                    .addComponent(AddSellRadio))
                .addGap(18, 18, 18)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Container.addTab("tab1", AddPnl);

        DeletePnl.setBackground(new java.awt.Color(29, 119, 117));
        DeletePnl.setName("DelPnl"); // NOI18N

        delete_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        delete_emp.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(delete_emp);

        SubmitDelet.setBackground(new java.awt.Color(33, 141, 138));
        SubmitDelet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitDelet.setForeground(new java.awt.Color(255, 255, 255));
        SubmitDelet.setText("Delete");
        SubmitDelet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDeletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeletePnlLayout = new javax.swing.GroupLayout(DeletePnl);
        DeletePnl.setLayout(DeletePnlLayout);
        DeletePnlLayout.setHorizontalGroup(
            DeletePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePnlLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeletePnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        DeletePnlLayout.setVerticalGroup(
            DeletePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        Container.addTab("tab2", DeletePnl);

        ListPnl.setBackground(new java.awt.Color(29, 119, 117));
        ListPnl.setName("ListPnl"); // NOI18N

        ViewTable.setBackground(new java.awt.Color(29, 119, 117));

        list_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Password", "RoleID"
            }
        ));
        list_emp.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ViewTable.setViewportView(list_emp);

        ListInvRadio.setBackground(new java.awt.Color(29, 119, 117));
        ListEmpRadio.add(ListInvRadio);
        ListInvRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListInvRadio.setForeground(new java.awt.Color(255, 255, 255));
        ListInvRadio.setText("Inventory");
        ListInvRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListInvRadioActionPerformed(evt);
            }
        });

        ListMarketRadio.setBackground(new java.awt.Color(29, 119, 117));
        ListEmpRadio.add(ListMarketRadio);
        ListMarketRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListMarketRadio.setForeground(new java.awt.Color(255, 255, 255));
        ListMarketRadio.setText("Market");
        ListMarketRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMarketRadioActionPerformed(evt);
            }
        });

        ListSellRadio.setBackground(new java.awt.Color(29, 119, 117));
        ListEmpRadio.add(ListSellRadio);
        ListSellRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListSellRadio.setForeground(new java.awt.Color(255, 255, 255));
        ListSellRadio.setText("Seller");
        ListSellRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListSellRadioActionPerformed(evt);
            }
        });

        UpdateEmp.setBackground(new java.awt.Color(33, 141, 138));
        UpdateEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateEmp.setForeground(new java.awt.Color(255, 255, 255));
        UpdateEmp.setText("Update");
        UpdateEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListPnlLayout = new javax.swing.GroupLayout(ListPnl);
        ListPnl.setLayout(ListPnlLayout);
        ListPnlLayout.setHorizontalGroup(
            ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewTable, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addGroup(ListPnlLayout.createSequentialGroup()
                .addGroup(ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListPnlLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(ListInvRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(ListMarketRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(ListSellRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListPnlLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(UpdateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListPnlLayout.setVerticalGroup(
            ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListSellRadio)
                    .addComponent(ListMarketRadio)
                    .addComponent(ListInvRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ViewTable, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        Container.addTab("tab3", ListPnl);

        SearchPnl.setBackground(new java.awt.Color(29, 119, 117));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(700, 200));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(700, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(700, 200));

        empID_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Password", "RoleID"
            }
        ));
        empID_search.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        empID_search.setMinimumSize(new java.awt.Dimension(60, 200));
        empID_search.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(empID_search);

        Search.setBackground(new java.awt.Color(33, 141, 138));
        Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        SearchEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmpIDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID to Search:");

        javax.swing.GroupLayout SearchPnlLayout = new javax.swing.GroupLayout(SearchPnl);
        SearchPnl.setLayout(SearchPnlLayout);
        SearchPnlLayout.setHorizontalGroup(
            SearchPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPnlLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(SearchEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SearchPnlLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SearchPnlLayout.setVerticalGroup(
            SearchPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchEmpID)
                    .addComponent(jLabel5)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Container.addTab("tab4", SearchPnl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Container)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(BTNpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BTNpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBTNActionPerformed
        EditProfile view = new EditProfile();
        view.setLocation(200, 150);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditProfileBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        Regestier view = new Regestier();
        view.setLocation(200, 150);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void UpdateBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTN1ActionPerformed
        Container.setSelectedIndex(2);
        a.view(list_emp);
    }//GEN-LAST:event_UpdateBTN1ActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        Container.setSelectedIndex(0);
    }//GEN-LAST:event_AddBTNActionPerformed

    private void DelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBTNActionPerformed
        Container.setSelectedIndex(1);
        a.view(delete_emp);
    }//GEN-LAST:event_DelBTNActionPerformed

    private void SubmitDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDeletActionPerformed
        a.delet(delete_emp);
    }//GEN-LAST:event_SubmitDeletActionPerformed

    private void SubmitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAddActionPerformed
        if (a.TextCheck(AddTxtField.getText()) && a.NumCheck(AddPassField.getText()) && a.NumCheck(AddIdField.getText())) {
            a.add(AddTxtField.getText(), AddPassField.getText(), Integer.parseInt(AddIdField.getText()), roleID);
            roleID = 0;
            AddEmpRdio.clearSelection();
            AddTxtField.setText("");
            AddPassField.setText("");
            AddIdField.setText("");
        }
    }//GEN-LAST:event_SubmitAddActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        if (a.NumCheck(SearchEmpID.getText()))
            a.search(Integer.parseInt(SearchEmpID.getText()), empID_search);
    }//GEN-LAST:event_SearchActionPerformed

    private void ListInvRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListInvRadioActionPerformed
        roleID = 2;
        a.List(roleID, list_emp);
    }//GEN-LAST:event_ListInvRadioActionPerformed

    private void ListMarketRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMarketRadioActionPerformed
        roleID = 3;
        a.List(roleID, list_emp);
    }//GEN-LAST:event_ListMarketRadioActionPerformed

    private void ListSellRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListSellRadioActionPerformed
        roleID = 4;
        a.List(roleID, list_emp);
    }//GEN-LAST:event_ListSellRadioActionPerformed

    private void AddInvRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInvRadioActionPerformed
        roleID = 2;
    }//GEN-LAST:event_AddInvRadioActionPerformed

    private void AddMarketRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMarketRadioActionPerformed
        roleID = 3;
    }//GEN-LAST:event_AddMarketRadioActionPerformed

    private void AddSellRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSellRadioActionPerformed
        roleID = 4;
    }//GEN-LAST:event_AddSellRadioActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        Container.setSelectedIndex(3);
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void AddTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTxtFieldActionPerformed

    private void SearchEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchEmpIDActionPerformed

    private void AddPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPassFieldActionPerformed

    private void UpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmpActionPerformed
        int row = list_emp.getSelectedRow();
        Object O = list_emp.getValueAt(row, 0);
        UpdateEmpFrame up = new UpdateEmpFrame(O);
        up.setLocation(200, 150);
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminFrame().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.ButtonGroup AddEmpRdio;
    private javax.swing.JTextField AddIdField;
    private javax.swing.JRadioButton AddInvRadio;
    private javax.swing.JRadioButton AddMarketRadio;
    private javax.swing.JPasswordField AddPassField;
    private javax.swing.JPanel AddPnl;
    private javax.swing.JRadioButton AddSellRadio;
    private javax.swing.JTextField AddTxtField;
    private javax.swing.JPanel BTNpnl;
    private javax.swing.JButton BackBTN;
    private javax.swing.JTabbedPane Container;
    private javax.swing.JButton DelBTN;
    private javax.swing.JPanel DeletePnl;
    private javax.swing.JButton EditProfileBTN;
    private javax.swing.ButtonGroup ListEmpRadio;
    private javax.swing.JRadioButton ListInvRadio;
    private javax.swing.JRadioButton ListMarketRadio;
    private javax.swing.JPanel ListPnl;
    private javax.swing.JRadioButton ListSellRadio;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchEmpID;
    private javax.swing.JPanel SearchPnl;
    private javax.swing.JButton SubmitAdd;
    private javax.swing.JButton SubmitDelet;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton UpdateBTN1;
    private javax.swing.JButton UpdateEmp;
    private javax.swing.JScrollPane ViewTable;
    private javax.swing.JTable delete_emp;
    private javax.swing.JTable empID_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable list_emp;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\Images\\Icon.png")));
    }
}
