/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Classes.Employee;
import java.awt.Toolkit;

/**
 *
 * @author Dell
 */
public class ForgetPass extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPass
     */
    public ForgetPass() {
        initComponents();

        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignInButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminRadio = new javax.swing.JRadioButton();
        InvEmpRadio = new javax.swing.JRadioButton();
        MarketEmpRadio = new javax.swing.JRadioButton();
        SaleEmpRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        GetPassButton = new javax.swing.JButton();
        UserNameField = new javax.swing.JTextField();
        BackBTN = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HYPER MARKET");
        setLocation(new java.awt.Point(70, 30));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("RegestierFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(29, 119, 117));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hyper Market");

        AdminRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(AdminRadio);
        AdminRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdminRadio.setForeground(new java.awt.Color(255, 255, 255));
        AdminRadio.setText("Adminstrator");
        AdminRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminRadioActionPerformed(evt);
            }
        });

        InvEmpRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(InvEmpRadio);
        InvEmpRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InvEmpRadio.setForeground(new java.awt.Color(255, 255, 255));
        InvEmpRadio.setText("Inventory Emp");
        InvEmpRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvEmpRadioActionPerformed(evt);
            }
        });

        MarketEmpRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(MarketEmpRadio);
        MarketEmpRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MarketEmpRadio.setForeground(new java.awt.Color(255, 255, 255));
        MarketEmpRadio.setText("Market Emp");
        MarketEmpRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarketEmpRadioActionPerformed(evt);
            }
        });

        SaleEmpRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(SaleEmpRadio);
        SaleEmpRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SaleEmpRadio.setForeground(new java.awt.Color(255, 255, 255));
        SaleEmpRadio.setText("Sale Emp");
        SaleEmpRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleEmpRadioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UserName:");

        GetPassButton.setBackground(new java.awt.Color(33, 141, 138));
        GetPassButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GetPassButton.setForeground(new java.awt.Color(255, 255, 255));
        GetPassButton.setText("Get Password");
        GetPassButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GetPassButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GetPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPassButtonActionPerformed(evt);
            }
        });

        BackBTN.setBackground(new java.awt.Color(33, 141, 138));
        BackBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setText("»");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GetPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDField)
                            .addComponent(UserNameField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminRadio)
                        .addGap(20, 20, 20)
                        .addComponent(InvEmpRadio)
                        .addGap(18, 18, 18)
                        .addComponent(MarketEmpRadio)
                        .addGap(18, 18, 18)
                        .addComponent(SaleEmpRadio))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InvEmpRadio)
                        .addComponent(AdminRadio))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaleEmpRadio)
                        .addComponent(MarketEmpRadio)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(GetPassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int roleID;
    private void AdminRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminRadioActionPerformed
        roleID = 1;
    }//GEN-LAST:event_AdminRadioActionPerformed

    private void InvEmpRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvEmpRadioActionPerformed
        roleID = 2;
    }//GEN-LAST:event_InvEmpRadioActionPerformed

    private void MarketEmpRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarketEmpRadioActionPerformed
        roleID = 3;
    }//GEN-LAST:event_MarketEmpRadioActionPerformed

    private void SaleEmpRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleEmpRadioActionPerformed
        roleID = 4;
    }//GEN-LAST:event_SaleEmpRadioActionPerformed

    private void GetPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPassButtonActionPerformed
        Employee emp = new Employee();
        if (emp.NumCheck(IDField.getText()) && emp.TextCheck(UserNameField.getText())) {
            emp.forgetPassword(IDField, UserNameField, roleID);
            roleID = 0;
            SignInButtonGroup.clearSelection();
        }
    }//GEN-LAST:event_GetPassButtonActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        Regestier view = new Regestier();
        view.setLocation(200, 150);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ForgetPass().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminRadio;
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton GetPassButton;
    private javax.swing.JTextField IDField;
    private javax.swing.JRadioButton InvEmpRadio;
    private javax.swing.JRadioButton MarketEmpRadio;
    private javax.swing.JRadioButton SaleEmpRadio;
    private javax.swing.ButtonGroup SignInButtonGroup;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\Images\\Icon.png")));
    }
}
