/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Classes.Inventory;
import Classes.Products;
import java.awt.Toolkit;
import javax.swing.JTable;

public class InvEmpFrame extends javax.swing.JFrame {
    
    Inventory inv_emp = new Inventory();
    Products p = new Products();
    int roleID;
    
    public JTable getListProduct() {
        return ListProduct;
    }
    
    public InvEmpFrame() {
        initComponents();
        
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listGroup = new javax.swing.ButtonGroup();
        AddGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();
        EditProfileBTN = new javax.swing.JButton();
        NotificationBTN = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BTNpnl = new javax.swing.JPanel();
        AddBTN = new javax.swing.JButton();
        DelBTN = new javax.swing.JButton();
        SearchBTN = new javax.swing.JButton();
        ListBTN = new javax.swing.JButton();
        Container = new javax.swing.JTabbedPane();
        AddPnl = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ProductName = new javax.swing.JTextField();
        ProductPrice = new javax.swing.JTextField();
        ProductQuant = new javax.swing.JTextField();
        ProductMinQuant = new javax.swing.JTextField();
        ProductEXdate = new javax.swing.JTextField();
        ProductID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SubmitAdding = new javax.swing.JButton();
        DeletePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        del_product = new javax.swing.JTable();
        SubmitDelet = new javax.swing.JButton();
        ListPnl = new javax.swing.JPanel();
        list_Table = new javax.swing.JScrollPane();
        ListProduct = new javax.swing.JTable();
        btnQuan = new javax.swing.JRadioButton();
        btnPrice = new javax.swing.JRadioButton();
        UpdateBTN = new javax.swing.JButton();
        Searchpnl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        SearchProdID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        search_prod_table = new javax.swing.JTable();
        Notifipnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        messages = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 119, 117));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hyper Market");

        BackBTN.setBackground(new java.awt.Color(33, 141, 138));
        BackBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setText("Home");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        EditProfileBTN.setBackground(new java.awt.Color(33, 141, 138));
        EditProfileBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EditProfileBTN.setForeground(new java.awt.Color(255, 255, 255));
        EditProfileBTN.setText("Edit Profile");
        EditProfileBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditProfileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileBTNActionPerformed(evt);
            }
        });

        NotificationBTN.setBackground(new java.awt.Color(33, 141, 138));
        NotificationBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NotificationBTN.setForeground(new java.awt.Color(255, 255, 255));
        NotificationBTN.setText("Notification");
        NotificationBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NotificationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationBTNActionPerformed(evt);
            }
        });

        BTNpnl.setBackground(new java.awt.Color(29, 119, 117));

        AddBTN.setBackground(new java.awt.Color(33, 141, 138));
        AddBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddBTN.setForeground(new java.awt.Color(255, 255, 255));
        AddBTN.setText("Add");
        AddBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        DelBTN.setBackground(new java.awt.Color(33, 141, 138));
        DelBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DelBTN.setForeground(new java.awt.Color(255, 255, 255));
        DelBTN.setText("Delete");
        DelBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBTNActionPerformed(evt);
            }
        });

        SearchBTN.setBackground(new java.awt.Color(33, 141, 138));
        SearchBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        SearchBTN.setText("Search");
        SearchBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        ListBTN.setBackground(new java.awt.Color(33, 141, 138));
        ListBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListBTN.setForeground(new java.awt.Color(255, 255, 255));
        ListBTN.setText("List");
        ListBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BTNpnlLayout = new javax.swing.GroupLayout(BTNpnl);
        BTNpnl.setLayout(BTNpnlLayout);
        BTNpnlLayout.setHorizontalGroup(
            BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNpnlLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(DelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(ListBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        BTNpnlLayout.setVerticalGroup(
            BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNpnlLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Container.setBackground(new java.awt.Color(29, 119, 117));
        Container.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        AddPnl.setBackground(new java.awt.Color(29, 119, 117));
        AddPnl.setName("AddPnl"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product EX-Date:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Quantity:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Price:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product ID:");

        ProductName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ProductPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ProductQuant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ProductMinQuant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ProductEXdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ProductID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Product Min Quantity:");

        SubmitAdding.setBackground(new java.awt.Color(33, 141, 138));
        SubmitAdding.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitAdding.setForeground(new java.awt.Color(255, 255, 255));
        SubmitAdding.setText("Submit Adding");
        SubmitAdding.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAddingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddPnlLayout = new javax.swing.GroupLayout(AddPnl);
        AddPnl.setLayout(AddPnlLayout);
        AddPnlLayout.setHorizontalGroup(
            AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPnlLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ProductEXdate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPnlLayout.createSequentialGroup()
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ProductQuant)
                            .addComponent(ProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductMinQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ProductName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        AddPnlLayout.setVerticalGroup(
            AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPnlLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ProductName))
                .addGap(18, 18, 18)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ProductPrice)
                    .addComponent(jLabel7)
                    .addComponent(ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ProductQuant)
                    .addComponent(jLabel11)
                    .addComponent(ProductMinQuant))
                .addGap(18, 18, 18)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ProductEXdate))
                .addGap(18, 18, 18)
                .addComponent(SubmitAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        Container.addTab("tab1", AddPnl);

        DeletePnl.setBackground(new java.awt.Color(29, 119, 117));
        DeletePnl.setName("DelPnl"); // NOI18N

        del_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        del_product.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(del_product);

        SubmitDelet.setBackground(new java.awt.Color(33, 141, 138));
        SubmitDelet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitDelet.setForeground(new java.awt.Color(255, 255, 255));
        SubmitDelet.setText("Delete");
        SubmitDelet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDeletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeletePnlLayout = new javax.swing.GroupLayout(DeletePnl);
        DeletePnl.setLayout(DeletePnlLayout);
        DeletePnlLayout.setHorizontalGroup(
            DeletePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePnlLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(DeletePnlLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(SubmitDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeletePnlLayout.setVerticalGroup(
            DeletePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletePnlLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        Container.addTab("tab2", DeletePnl);

        ListPnl.setBackground(new java.awt.Color(29, 119, 117));
        ListPnl.setName("ListPnl"); // NOI18N

        list_Table.setBackground(new java.awt.Color(29, 119, 117));

        ListProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListProduct.setSelectionBackground(new java.awt.Color(0, 153, 153));
        list_Table.setViewportView(ListProduct);

        btnQuan.setBackground(new java.awt.Color(29, 119, 117));
        listGroup.add(btnQuan);
        btnQuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuan.setForeground(new java.awt.Color(255, 255, 255));
        btnQuan.setText("Quantity");
        btnQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanActionPerformed(evt);
            }
        });

        btnPrice.setBackground(new java.awt.Color(29, 119, 117));
        listGroup.add(btnPrice);
        btnPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrice.setForeground(new java.awt.Color(255, 255, 255));
        btnPrice.setText("Price");
        btnPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceActionPerformed(evt);
            }
        });

        UpdateBTN.setBackground(new java.awt.Color(33, 141, 138));
        UpdateBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBTN.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBTN.setText("Update");
        UpdateBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListPnlLayout = new javax.swing.GroupLayout(ListPnl);
        ListPnl.setLayout(ListPnlLayout);
        ListPnlLayout.setHorizontalGroup(
            ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPnlLayout.createSequentialGroup()
                .addGroup(ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListPnlLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(btnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListPnlLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(list_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        ListPnlLayout.setVerticalGroup(
            ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrice)
                    .addComponent(btnQuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(list_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Container.addTab("tab3", ListPnl);

        Searchpnl.setBackground(new java.awt.Color(29, 119, 117));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID to Search:");

        Search.setBackground(new java.awt.Color(33, 141, 138));
        Search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        SearchProdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchProdIDActionPerformed(evt);
            }
        });

        jScrollPane2.setMaximumSize(new java.awt.Dimension(700, 200));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(700, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(700, 200));

        search_prod_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        search_prod_table.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        search_prod_table.setMinimumSize(new java.awt.Dimension(60, 200));
        search_prod_table.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(search_prod_table);

        javax.swing.GroupLayout SearchpnlLayout = new javax.swing.GroupLayout(Searchpnl);
        Searchpnl.setLayout(SearchpnlLayout);
        SearchpnlLayout.setHorizontalGroup(
            SearchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchpnlLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(SearchProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(SearchpnlLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        SearchpnlLayout.setVerticalGroup(
            SearchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchProdID)
                    .addComponent(jLabel5)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Container.addTab("tab4", Searchpnl);

        Notifipnl.setBackground(new java.awt.Color(29, 119, 117));

        messages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(messages);

        javax.swing.GroupLayout NotifipnlLayout = new javax.swing.GroupLayout(Notifipnl);
        Notifipnl.setLayout(NotifipnlLayout);
        NotifipnlLayout.setHorizontalGroup(
            NotifipnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotifipnlLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        NotifipnlLayout.setVerticalGroup(
            NotifipnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotifipnlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Container.addTab("tab5", Notifipnl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NotificationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NotificationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        Regestier view = new Regestier();
        view.setLocation(200, 150);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void EditProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBTNActionPerformed
        EditProfile view = new EditProfile();
        view.setLocation(200, 150);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditProfileBTNActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        Container.setSelectedIndex(0);
    }//GEN-LAST:event_AddBTNActionPerformed

    private void DelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBTNActionPerformed
        Container.setSelectedIndex(1);
        inv_emp.view(del_product);
    }//GEN-LAST:event_DelBTNActionPerformed

    private void ListBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListBTNActionPerformed
        Container.setSelectedIndex(2);
        inv_emp.view(ListProduct);
    }//GEN-LAST:event_ListBTNActionPerformed

    private void SubmitDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDeletActionPerformed
        inv_emp.delete_Product(del_product);
    }//GEN-LAST:event_SubmitDeletActionPerformed

    private void NotificationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationBTNActionPerformed
        
        Container.setSelectedIndex(4);
        inv_emp.viewNot(messages);
    }//GEN-LAST:event_NotificationBTNActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        if (inv_emp.NumCheck(SearchProdID.getText()))
            inv_emp.search(SearchProdID, search_prod_table);
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        Container.setSelectedIndex(3);
        inv_emp.setTableTitle(search_prod_table);
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void btnQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanActionPerformed
        inv_emp.list_Quant(ListProduct);
    }//GEN-LAST:event_btnQuanActionPerformed

    private void btnPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceActionPerformed
        inv_emp.list_Price(ListProduct);
    }//GEN-LAST:event_btnPriceActionPerformed

    private void SearchProdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchProdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchProdIDActionPerformed

    private void SubmitAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAddingActionPerformed
        if (inv_emp.NumCheck(ProductID.getText()) && inv_emp.TextCheck(ProductName.getText()) && inv_emp.NumCheck(ProductPrice.getText()) && inv_emp.NumCheck(ProductQuant.getText()) && inv_emp.NumCheck(ProductMinQuant.getText()) && inv_emp.DateCheck(ProductEXdate.getText())) {
            Products pr = new Products(Integer.parseInt(ProductID.getText()), ProductName.getText(), Double.parseDouble(ProductPrice.getText()), Integer.parseInt(ProductQuant.getText()), Integer.parseInt(ProductMinQuant.getText()), ProductEXdate.getText());
            inv_emp.AddNew(pr);
        }
    }//GEN-LAST:event_SubmitAddingActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        int row = ListProduct.getSelectedRow();
        Object O = ListProduct.getValueAt(row, 0);
        UpdatProductFrame up = new UpdatProductFrame(O);
        up.setLocation(200, 150);
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InvEmpFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.ButtonGroup AddGroup;
    private javax.swing.JPanel AddPnl;
    private javax.swing.JPanel BTNpnl;
    private javax.swing.JButton BackBTN;
    private javax.swing.JTabbedPane Container;
    private javax.swing.JButton DelBTN;
    private javax.swing.JPanel DeletePnl;
    private javax.swing.JButton EditProfileBTN;
    private javax.swing.JButton ListBTN;
    private javax.swing.JPanel ListPnl;
    private javax.swing.JTable ListProduct;
    private javax.swing.JButton NotificationBTN;
    private javax.swing.JPanel Notifipnl;
    private javax.swing.JTextField ProductEXdate;
    private javax.swing.JTextField ProductID;
    private javax.swing.JTextField ProductMinQuant;
    private javax.swing.JTextField ProductName;
    private javax.swing.JTextField ProductPrice;
    private javax.swing.JTextField ProductQuant;
    private javax.swing.JButton Search;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JTextField SearchProdID;
    private javax.swing.JPanel Searchpnl;
    private javax.swing.JButton SubmitAdding;
    private javax.swing.JButton SubmitDelet;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JRadioButton btnPrice;
    private javax.swing.JRadioButton btnQuan;
    private javax.swing.JTable del_product;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup listGroup;
    private javax.swing.JScrollPane list_Table;
    private javax.swing.JTable messages;
    private javax.swing.JTable search_prod_table;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\Images\\Icon.png")));
    }
}
