/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Classes.Inventory;
import Classes.Market;
import java.awt.Toolkit;

/**
 *
 * @author Dell
 */
public class MarketEmpFrame extends javax.swing.JFrame {

    Inventory invEmp = new Inventory();
    Market mar = new Market();

    public MarketEmpFrame() {
        initComponents();

        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GpBTNReport = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();
        EditProfileBTN = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BTNpnl = new javax.swing.JPanel();
        AddBTN = new javax.swing.JButton();
        UpdateBTN1 = new javax.swing.JButton();
        viewOffer = new javax.swing.JButton();
        Container = new javax.swing.JTabbedPane();
        AddOfferPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idOfferTxtField = new javax.swing.JTextField();
        offerDateTxtField = new javax.swing.JTextField();
        discOfferTxtField = new javax.swing.JTextField();
        SubmitAdd = new javax.swing.JButton();
        ReportPnl = new javax.swing.JPanel();
        ViewTable = new javax.swing.JScrollPane();
        prodTable = new javax.swing.JTable();
        ExDateRadio = new javax.swing.JRadioButton();
        PriceRadio = new javax.swing.JRadioButton();
        viewAllOffers = new javax.swing.JTabbedPane();
        viewTable = new javax.swing.JScrollPane();
        AllOffers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 490));
        setMinimumSize(new java.awt.Dimension(700, 490));
        setPreferredSize(new java.awt.Dimension(700, 490));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 119, 117));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hyper Market");

        BackBTN.setBackground(new java.awt.Color(33, 141, 138));
        BackBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(255, 255, 255));
        BackBTN.setText("Home");
        BackBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        EditProfileBTN.setBackground(new java.awt.Color(33, 141, 138));
        EditProfileBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EditProfileBTN.setForeground(new java.awt.Color(255, 255, 255));
        EditProfileBTN.setText("Edit Profile");
        EditProfileBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditProfileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileBTNActionPerformed(evt);
            }
        });

        BTNpnl.setBackground(new java.awt.Color(29, 119, 117));

        AddBTN.setBackground(new java.awt.Color(33, 141, 138));
        AddBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddBTN.setForeground(new java.awt.Color(255, 255, 255));
        AddBTN.setText("Add Offer");
        AddBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        UpdateBTN1.setBackground(new java.awt.Color(33, 141, 138));
        UpdateBTN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBTN1.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBTN1.setText("Report");
        UpdateBTN1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTN1ActionPerformed(evt);
            }
        });

        viewOffer.setBackground(new java.awt.Color(33, 141, 138));
        viewOffer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewOffer.setForeground(new java.awt.Color(255, 255, 255));
        viewOffer.setText("View Offers");
        viewOffer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOfferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BTNpnlLayout = new javax.swing.GroupLayout(BTNpnl);
        BTNpnl.setLayout(BTNpnlLayout);
        BTNpnlLayout.setHorizontalGroup(
            BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BTNpnlLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(UpdateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(viewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        BTNpnlLayout.setVerticalGroup(
            BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNpnlLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(BTNpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Container.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        AddOfferPnl.setBackground(new java.awt.Color(29, 119, 117));
        AddOfferPnl.setName("AddOfferPnl"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Offer ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Discount");

        SubmitAdd.setBackground(new java.awt.Color(33, 141, 138));
        SubmitAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitAdd.setForeground(new java.awt.Color(255, 255, 255));
        SubmitAdd.setText("Submit");
        SubmitAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddOfferPnlLayout = new javax.swing.GroupLayout(AddOfferPnl);
        AddOfferPnl.setLayout(AddOfferPnlLayout);
        AddOfferPnlLayout.setHorizontalGroup(
            AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddOfferPnlLayout.createSequentialGroup()
                .addGroup(AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddOfferPnlLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idOfferTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(offerDateTxtField)
                            .addComponent(discOfferTxtField)))
                    .addGroup(AddOfferPnlLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(SubmitAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        AddOfferPnlLayout.setVerticalGroup(
            AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddOfferPnlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idOfferTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(offerDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(AddOfferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discOfferTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        Container.addTab("tab1", AddOfferPnl);

        ReportPnl.setBackground(new java.awt.Color(29, 119, 117));
        ReportPnl.setName("ReportPnl"); // NOI18N

        ViewTable.setBackground(new java.awt.Color(29, 119, 117));

        prodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        prodTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ViewTable.setViewportView(prodTable);

        ExDateRadio.setBackground(new java.awt.Color(29, 119, 117));
        GpBTNReport.add(ExDateRadio);
        ExDateRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExDateRadio.setForeground(new java.awt.Color(255, 255, 255));
        ExDateRadio.setText("Expire date");
        ExDateRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExDateRadioActionPerformed(evt);
            }
        });

        PriceRadio.setBackground(new java.awt.Color(29, 119, 117));
        GpBTNReport.add(PriceRadio);
        PriceRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PriceRadio.setForeground(new java.awt.Color(255, 255, 255));
        PriceRadio.setText("Price");
        PriceRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportPnlLayout = new javax.swing.GroupLayout(ReportPnl);
        ReportPnl.setLayout(ReportPnlLayout);
        ReportPnlLayout.setHorizontalGroup(
            ReportPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportPnlLayout.createSequentialGroup()
                .addComponent(ViewTable, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(ReportPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PriceRadio)
                .addGap(103, 103, 103)
                .addComponent(ExDateRadio)
                .addGap(280, 280, 280))
        );
        ReportPnlLayout.setVerticalGroup(
            ReportPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportPnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ReportPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceRadio)
                    .addComponent(ExDateRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(ViewTable, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Container.addTab("tab3", ReportPnl);

        viewAllOffers.setBackground(new java.awt.Color(29, 119, 117));
        viewAllOffers.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        AllOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AllOffers.setMaximumSize(new java.awt.Dimension(700, 490));
        AllOffers.setMinimumSize(new java.awt.Dimension(700, 490));
        AllOffers.setPreferredSize(new java.awt.Dimension(700, 490));
        AllOffers.setSelectionBackground(new java.awt.Color(0, 153, 153));
        viewTable.setViewportView(AllOffers);

        viewAllOffers.addTab("tab1", viewTable);

        Container.addTab("tab3", viewAllOffers);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Container)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        Regestier view = new Regestier();
        view.setLocation(200, 150);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void EditProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBTNActionPerformed
        EditProfile view = new EditProfile();
        view.setLocation(200, 150);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditProfileBTNActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        Container.setSelectedIndex(0);
    }//GEN-LAST:event_AddBTNActionPerformed

    private void UpdateBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTN1ActionPerformed
        Container.setSelectedIndex(1);

        invEmp.view(prodTable);
    }//GEN-LAST:event_UpdateBTN1ActionPerformed

    private void SubmitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAddActionPerformed
        if (mar.NumCheck(idOfferTxtField.getText()) && mar.DateCheck(offerDateTxtField.getText()) && mar.NumCheck(discOfferTxtField.getText())) {
            Market m = new Market(Integer.parseInt(idOfferTxtField.getText()), offerDateTxtField.getText(), Integer.parseInt(discOfferTxtField.getText()));
            mar.addOffer(m);
        }
    }//GEN-LAST:event_SubmitAddActionPerformed

    private void PriceRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceRadioActionPerformed
        invEmp.list_Price(prodTable);
    }//GEN-LAST:event_PriceRadioActionPerformed

    private void ExDateRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExDateRadioActionPerformed
        mar.expireDateReport(prodTable);
    }//GEN-LAST:event_ExDateRadioActionPerformed

    private void viewOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOfferActionPerformed
        Container.setSelectedIndex(2);
        mar.viewOffers(AllOffers);
    }//GEN-LAST:event_viewOfferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketEmpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JPanel AddOfferPnl;
    private javax.swing.JTable AllOffers;
    private javax.swing.JPanel BTNpnl;
    private javax.swing.JButton BackBTN;
    private javax.swing.JTabbedPane Container;
    private javax.swing.JButton EditProfileBTN;
    private javax.swing.JRadioButton ExDateRadio;
    private javax.swing.ButtonGroup GpBTNReport;
    private javax.swing.JRadioButton PriceRadio;
    private javax.swing.JPanel ReportPnl;
    private javax.swing.JButton SubmitAdd;
    private javax.swing.JButton UpdateBTN1;
    private javax.swing.JScrollPane ViewTable;
    private javax.swing.JTextField discOfferTxtField;
    private javax.swing.JTextField idOfferTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField offerDateTxtField;
    private javax.swing.JTable prodTable;
    private javax.swing.JTabbedPane viewAllOffers;
    private javax.swing.JButton viewOffer;
    private javax.swing.JScrollPane viewTable;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\Images\\Icon.png")));
    }
}
