/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Classes.regestration;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Regestier extends javax.swing.JFrame {
regestration r = new regestration(); 
    /**
     * Creates new form Regestier
     */
    public Regestier() {
        initComponents();
        
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignInButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminRadio = new javax.swing.JRadioButton();
        InvEmpRadio = new javax.swing.JRadioButton();
        MarketEmpRadio = new javax.swing.JRadioButton();
        SaleEmpRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        SignInBTN = new javax.swing.JButton();
        forgetButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HYPER MARKET");
        setLocation(new java.awt.Point(200, 150));
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("RegestierFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(29, 119, 117));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hyper Market");

        AdminRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(AdminRadio);
        AdminRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdminRadio.setForeground(new java.awt.Color(255, 255, 255));
        AdminRadio.setText("Adminstrator");

        InvEmpRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(InvEmpRadio);
        InvEmpRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InvEmpRadio.setForeground(new java.awt.Color(255, 255, 255));
        InvEmpRadio.setText("Inventory Emp");

        MarketEmpRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(MarketEmpRadio);
        MarketEmpRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MarketEmpRadio.setForeground(new java.awt.Color(255, 255, 255));
        MarketEmpRadio.setText("Market Emp");

        SaleEmpRadio.setBackground(new java.awt.Color(29, 119, 117));
        SignInButtonGroup.add(SaleEmpRadio);
        SaleEmpRadio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SaleEmpRadio.setForeground(new java.awt.Color(255, 255, 255));
        SaleEmpRadio.setText("Sale Emp");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        SignInBTN.setBackground(new java.awt.Color(33, 141, 138));
        SignInBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SignInBTN.setForeground(new java.awt.Color(255, 255, 255));
        SignInBTN.setText("Sign In");
        SignInBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignInBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignInBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBTNActionPerformed(evt);
            }
        });

        forgetButton.setBackground(new java.awt.Color(33, 141, 138));
        forgetButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forgetButton.setForeground(new java.awt.Color(255, 255, 255));
        forgetButton.setText("Forget My Password");
        forgetButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        forgetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdminRadio)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(InvEmpRadio)
                                .addGap(18, 18, 18)
                                .addComponent(MarketEmpRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(SaleEmpRadio))
                            .addComponent(UserNameField)
                            .addComponent(PasswordField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(forgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SignInBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InvEmpRadio)
                        .addComponent(AdminRadio))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaleEmpRadio)
                        .addComponent(MarketEmpRadio)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(PasswordField))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignInBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBTNActionPerformed
        int roleid;
                if (AdminRadio.isSelected()) 
                {
                    roleid = 1;
                    if (r.cheackNameAndPass(UserNameField.getText(), PasswordField.getText(),Integer.toString(roleid)))
                    {
                    // Check UserName\ID And Password
                    AdminFrame view = new AdminFrame();
                    view.setLocation(200, 150);
                    view.setVisible(true);
                    this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "invalid id or password or role", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                 else if (InvEmpRadio.isSelected()) 
                 {
                     roleid = 2;
                    if (r.cheackNameAndPass(UserNameField.getText(), PasswordField.getText(),Integer.toString(roleid)))
                    {
                        InvEmpFrame view = new InvEmpFrame();
                        view.setLocation(200, 150);
                        view.setVisible(true);
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "invalid id or password or role", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } 
                else if (MarketEmpRadio.isSelected()) 
                {
                    roleid = 3;
                    if (r.cheackNameAndPass(UserNameField.getText(), PasswordField.getText(), Integer.toString(roleid)))
                    {
                    MarketEmpFrame view = new MarketEmpFrame();
                    view.setLocation(200, 150);
                    view.setVisible(true);
                    this.dispose();
                    }
                else
                    {
                        JOptionPane.showMessageDialog(null, "invalid id or password or role", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else if (SaleEmpRadio.isSelected()) 
                {
                    roleid = 4;
                    if (r.cheackNameAndPass(UserNameField.getText(), PasswordField.getText(), Integer.toString(roleid)))
                    {
                    SellEmpFrame view = new SellEmpFrame();
                    view.setLocation(200, 150);
                    view.setVisible(true);
                    this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "invalid id or password or role ", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else 
                {
                    JOptionPane.showMessageDialog(null, "Please choose your role..", "Message", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_SignInBTNActionPerformed

    private void forgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetButtonActionPerformed
        ForgetPass fp = new ForgetPass();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regestier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regestier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regestier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regestier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Regestier().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminRadio;
    private javax.swing.JRadioButton InvEmpRadio;
    private javax.swing.JRadioButton MarketEmpRadio;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JRadioButton SaleEmpRadio;
    private javax.swing.JButton SignInBTN;
    private javax.swing.ButtonGroup SignInButtonGroup;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JButton forgetButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\Images\\Icon.png")));
    }
}
